spring:
  mvc :
    throw-exception-if-no-handler-found: true
  resources:
    add-mappings : false
  profiles: local
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://localhost:3306/trade
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
server:
  port: 8001
jwt:
  secret : '[jwt-secret]+$YWvnSnaUXByBrDzub4WZUQc8uTNHRtAuowqFKhJ5tGvRicxwEkurkzRGTxjZN2dQJe24RbQlhTAaaJ9uGLj7AgUnZqxuoN7XiLSu$'
mail:
  protocol : smtps
  username : your application email
  password : your password
  from: your application email
  subject: Trade - Forget Password
  smtpserver : smtp.gmail.com
  host : mail.smtp.host
  auth : mail.smtp.auth
  port : mail.smtp.port
  defaultport : 465
  starttls : mail.smtp.starttls.enable
  starttlsrequired : mail.smtp.starttls.required
